name: Docker Publish

on:
  push:
    branches:
      - 'main'

env:
  DOCKER_USER: ecsupport
  DOCKER_REGISTRY: docker.io
  DOCKER_REPO: zephyr-ci

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Tag
      id: docker_tag
      run: |
        # If push due to a normal commit to main GITHUB_REF will look like
        # refs/heads/main convert that to 'latest'
        if [ ${GITHUB_REF} == "refs/heads/main" ]; then
           echo ::set-output name=DOCKER_TAG::latest;
        else
           # If push due to a tag GITHUB_REF will look like refs/tags/TAG-FOO
           # chop of 'refs/tags' so DOCKER_TAG=TAG-FOO
           echo ::set-output name=DOCKER_TAG::${GITHUB_REF/refs\/tags\//};
        fi

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - uses: actions/checkout@v2

    - name: build
      env:
        DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
      run: |
        docker build . --file Dockerfile --tag ${DOCKER_REGISTRY}/${{ github.repository_owner }}/${DOCKER_REPO}:${DOCKER_TAG}


    - name: push
      env:
        DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
      run: |
        docker push ${DOCKER_REGISTRY}/${{ github.repository_owner }}/${DOCKER_REPO}:${DOCKER_TAG}
